<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>kuka_kl_support</name>
  <version>2.0.2</version>
  <description>Robot model for the KUKA KL family</description>
  <maintainer email="tamas.pepo@kuka.com">Tamas Pepo</maintainer>
  <maintainer email="aron.svastits@kuka.com">Aron Svastits</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>urdf</depend>
  <depend>xacro</depend>
  <export>
    <architecture_independent/>
    <build_type>ament_cmake</build_type>
  </export>
</package>
